// src/literature/curatedResources.ts
// Curated external resource data for Stories 20-7 through 20-12
// Documentaries, TV Shows, YouTube Channels, Books, Museums, Online Simulators

/** Resource type categories matching stories 20-7 through 20-12 */
export type CuratedResourceType =
  | 'documentary'
  | 'tv'
  | 'youtube'
  | 'book'
  | 'museum'
  | 'simulator';

/** Display labels for each resource type */
export const RESOURCE_TYPE_LABELS: Record<CuratedResourceType, string> = {
  documentary: 'Documentaries & Films',
  tv: 'TV Shows & Series',
  youtube: 'YouTube Channels',
  book: 'Books',
  museum: 'Museums & Sites',
  simulator: 'Online Simulators',
};

/** Icons for each resource type */
export const RESOURCE_TYPE_ICONS: Record<CuratedResourceType, string> = {
  documentary: '\uD83C\uDFAC',  // 🎬
  tv: '\uD83D\uDCFA',           // 📺
  youtube: '\u25B6\uFE0F',      // ▶️
  book: '\uD83D\uDCDA',         // 📚
  museum: '\uD83C\uDFDB\uFE0F', // 🏛️
  simulator: '\uD83D\uDD27',    // 🔧
};

/** Rendering order for resource type sections */
export const RESOURCE_TYPE_ORDER: readonly CuratedResourceType[] = [
  'documentary', 'tv', 'youtube', 'book', 'museum', 'simulator',
] as const;

/** A single curated external resource */
export interface CuratedResource {
  readonly id: string;
  readonly type: CuratedResourceType;
  readonly title: string;
  readonly year?: number;
  readonly creator?: string;
  readonly era: string;
  readonly description: string;
  readonly whereToAccess: string;
  readonly tags: readonly string[];
}

// --- Story 20.7: Documentaries & Films ---

const DOCUMENTARIES: readonly CuratedResource[] = [
  {
    id: 'doc-01',
    type: 'documentary',
    title: 'The Imitation Game',
    year: 2014,
    creator: 'Morten Tyldum',
    era: 'Turing Era',
    description: 'The story of Alan Turing cracking the Enigma code during WWII, dramatizing the birth of computational thinking and the first electronic computers.',
    whereToAccess: 'Netflix, Amazon Prime',
    tags: ['turing', 'enigma', 'wwii', 'codebreaking'],
  },
  {
    id: 'doc-02',
    type: 'documentary',
    title: 'Hidden Figures',
    year: 2016,
    creator: 'Theodore Melfi',
    era: 'Early Computing',
    description: 'Three brilliant African-American women at NASA who served as human computers and helped launch astronaut John Glenn into orbit.',
    whereToAccess: 'Disney+, Amazon Prime',
    tags: ['nasa', 'human-computers', 'space-race', 'early-computing'],
  },
  {
    id: 'doc-03',
    type: 'documentary',
    title: 'Pirates of Silicon Valley',
    year: 1999,
    creator: 'Martyn Burke',
    era: 'PC Era',
    description: 'The rivalry between Steve Jobs and Bill Gates as they built Apple and Microsoft, capturing the chaotic creativity of the personal computer revolution.',
    whereToAccess: 'YouTube, Amazon Prime',
    tags: ['apple', 'microsoft', 'pc-revolution', 'jobs', 'gates'],
  },
  {
    id: 'doc-04',
    type: 'documentary',
    title: 'Triumph of the Nerds',
    year: 1996,
    creator: 'Robert X. Cringely',
    era: 'PC Era',
    description: 'PBS documentary tracing the personal computer from hobbyist garages to mainstream dominance, featuring interviews with key figures.',
    whereToAccess: 'YouTube',
    tags: ['pc-revolution', 'ibm', 'apple', 'microsoft', 'hobbyist'],
  },
  {
    id: 'doc-05',
    type: 'documentary',
    title: 'The Machine That Changed the World',
    year: 1992,
    creator: 'PBS/WGBH',
    era: 'All Eras',
    description: 'Five-part PBS series covering the entire history of computing from Babbage to modern networks, with rare archival footage.',
    whereToAccess: 'YouTube, PBS',
    tags: ['history', 'babbage', 'mainframe', 'pc', 'network'],
  },
  {
    id: 'doc-06',
    type: 'documentary',
    title: 'Revolution OS',
    year: 2001,
    creator: 'J.T.S. Moore',
    era: 'Open Source',
    description: 'The story of Linux and the open-source movement, featuring Linus Torvalds, Richard Stallman, and the philosophy behind free software.',
    whereToAccess: 'YouTube',
    tags: ['linux', 'open-source', 'stallman', 'torvalds'],
  },
  {
    id: 'doc-07',
    type: 'documentary',
    title: 'Silicon Cowboys',
    year: 2016,
    creator: 'Jason Cohen',
    era: 'PC Era',
    description: 'How three friends in Texas built Compaq Computer and challenged IBM for dominance of the PC market through reverse engineering.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['compaq', 'ibm', 'reverse-engineering', 'pc-clone'],
  },
  {
    id: 'doc-08',
    type: 'documentary',
    title: 'General Magic',
    year: 2018,
    creator: 'Sarah Kerruish & Matt Maude',
    era: 'Early Mobile',
    description: 'The untold story of the team that invented the smartphone a decade before the iPhone, and how their vision was too early for its time.',
    whereToAccess: 'Amazon Prime, Apple TV+',
    tags: ['mobile', 'smartphone', 'apple', 'innovation'],
  },
  {
    id: 'doc-09',
    type: 'documentary',
    title: 'Micro Men',
    year: 2009,
    creator: 'BBC',
    era: '8-bit Era',
    description: 'BBC drama about the rivalry between Clive Sinclair and Chris Curry as they battled to bring computers into British homes in the 1980s.',
    whereToAccess: 'YouTube, BBC iPlayer',
    tags: ['sinclair', 'acorn', 'bbc-micro', '8-bit', 'british-computing'],
  },
  {
    id: 'doc-10',
    type: 'documentary',
    title: 'BBS: The Documentary',
    year: 2005,
    creator: 'Jason Scott',
    era: 'Modem Era',
    description: 'Eight-part documentary about the bulletin board system (BBS) subculture of the 1980s-90s, the internet before the internet.',
    whereToAccess: 'YouTube, Archive.org',
    tags: ['bbs', 'modem', 'dial-up', 'online-culture'],
  },
  {
    id: 'doc-11',
    type: 'documentary',
    title: 'The Code',
    year: 2001,
    creator: 'Hannu Puttonen',
    era: 'Open Source',
    description: 'Finnish documentary exploring the Linux operating system, Linus Torvalds, and the global community that built an OS to rival Microsoft.',
    whereToAccess: 'YouTube',
    tags: ['linux', 'open-source', 'torvalds', 'community'],
  },
  {
    id: 'doc-12',
    type: 'documentary',
    title: 'Steve Jobs: The Man in the Machine',
    year: 2015,
    creator: 'Alex Gibney',
    era: 'PC Era to Modern',
    description: 'Unflinching look at the complicated genius behind Apple, from the Apple II through the iPhone, examining the human cost of innovation.',
    whereToAccess: 'Amazon Prime',
    tags: ['apple', 'jobs', 'iphone', 'innovation'],
  },
  {
    id: 'doc-13',
    type: 'documentary',
    title: 'Lo and Behold: Reveries of the Connected World',
    year: 2016,
    creator: 'Werner Herzog',
    era: 'Internet Era',
    description: 'Werner Herzog explores the origins and future of the internet, from the first message sent on ARPANET to AI and cybersecurity, asking what the connected world means for humanity.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['internet', 'arpanet', 'ai', 'cybersecurity', 'herzog'],
  },
  {
    id: 'doc-14',
    type: 'documentary',
    title: "The Internet's Own Boy: The Story of Aaron Swartz",
    year: 2014,
    creator: 'Brian Knappenberger',
    era: 'Internet Freedom',
    description: 'The life of programming prodigy Aaron Swartz, who helped create RSS and Reddit, and his fight for open access to information that made him a symbol of internet freedom.',
    whereToAccess: 'YouTube, Amazon Prime',
    tags: ['internet', 'open-access', 'activism', 'programming'],
  },
  {
    id: 'doc-15',
    type: 'documentary',
    title: 'AlphaGo',
    year: 2017,
    creator: 'Greg Kohs',
    era: 'AI Era',
    description: 'DeepMind\'s AI takes on the world champion of Go, a game thought to be decades away from computer mastery. A stunning look at the moment machines surpassed human intuition.',
    whereToAccess: 'YouTube (free)',
    tags: ['ai', 'deepmind', 'machine-learning', 'go', 'neural-network'],
  },
  {
    id: 'doc-16',
    type: 'documentary',
    title: 'Codebreaker',
    year: 2011,
    creator: 'Clare Beavan',
    era: 'Turing Era',
    description: 'Documentary about Alan Turing\'s life, his pivotal role in cracking Enigma, his pioneering work on machine intelligence, and his tragic persecution.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['turing', 'enigma', 'ai', 'biography', 'codebreaking'],
  },
  {
    id: 'doc-17',
    type: 'documentary',
    title: 'Code Rush',
    year: 2000,
    creator: 'David Winton',
    era: 'Browser Wars',
    description: 'Inside Netscape during its final year as a company, as engineers race to open-source the browser code that would become Mozilla Firefox.',
    whereToAccess: 'YouTube, Archive.org',
    tags: ['netscape', 'mozilla', 'open-source', 'browser-wars', 'startup'],
  },
  {
    id: 'doc-18',
    type: 'documentary',
    title: 'Something Ventured',
    year: 2011,
    creator: 'Daniel Geller & Dayna Goldfine',
    era: 'Silicon Valley Origins',
    description: 'How venture capital created Silicon Valley, featuring the investors behind Intel, Apple, Atari, Genentech, and Cisco, and the risks they took on unknown founders.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['venture-capital', 'silicon-valley', 'intel', 'startup', 'investment'],
  },
  {
    id: 'doc-19',
    type: 'documentary',
    title: 'The KGB, the Computer, and Me',
    year: 1990,
    creator: 'PBS/NOVA',
    era: 'Cold War Computing',
    description: 'Astronomer Clifford Stoll tracks a 75-cent accounting error to a KGB-backed hacker infiltrating US military computers, becoming one of the first cyber detective stories.',
    whereToAccess: 'YouTube',
    tags: ['hacking', 'kgb', 'cold-war', 'cybersecurity', 'stoll'],
  },
  {
    id: 'doc-20',
    type: 'documentary',
    title: 'All Watched Over by Machines of Loving Grace',
    year: 2011,
    creator: 'Adam Curtis / BBC',
    era: 'All Eras',
    description: 'Three-part BBC series examining how computers and cybernetics shaped our understanding of the world, from Silicon Valley utopianism to ecosystems to global finance.',
    whereToAccess: 'YouTube, BBC iPlayer',
    tags: ['cybernetics', 'silicon-valley', 'systems-theory', 'society', 'ideology'],
  },
  {
    id: 'doc-21',
    type: 'documentary',
    title: 'Zero Days',
    year: 2016,
    creator: 'Alex Gibney',
    era: 'Cyber Warfare',
    description: 'Investigation into Stuxnet, the computer worm that destroyed Iranian nuclear centrifuges, revealing the dawn of state-sponsored cyber warfare.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['stuxnet', 'cyber-warfare', 'security', 'iran', 'nsa'],
  },
  {
    id: 'doc-22',
    type: 'documentary',
    title: 'We Are Legion: The Story of the Hacktivists',
    year: 2012,
    creator: 'Brian Knappenberger',
    era: 'Internet Era',
    description: 'The history of Anonymous, from pranksters on 4chan to a global force for digital activism, exploring hacktivism and the politics of the internet.',
    whereToAccess: 'YouTube, Amazon Prime',
    tags: ['anonymous', 'hacktivism', 'internet', 'activism', 'hacking'],
  },
  {
    id: 'doc-23',
    type: 'documentary',
    title: 'TPB AFK: The Pirate Bay Away From Keyboard',
    year: 2013,
    creator: 'Simon Klose',
    era: 'Internet Era',
    description: 'Follows the founders of The Pirate Bay through their trial, exploring digital piracy, copyright, and what it means to share information in the internet age.',
    whereToAccess: 'YouTube (free)',
    tags: ['piracy', 'copyright', 'internet', 'file-sharing', 'trial'],
  },
  {
    id: 'doc-24',
    type: 'documentary',
    title: 'Nerds 2.0.1: A Brief History of the Internet',
    year: 1998,
    creator: 'Robert X. Cringely / PBS',
    era: 'Internet Origins',
    description: 'The sequel to Triumph of the Nerds, tracing the internet from ARPANET through the dot-com boom, with interviews from the people who wired the world.',
    whereToAccess: 'YouTube',
    tags: ['internet', 'arpanet', 'dot-com', 'networking', 'www'],
  },
  {
    id: 'doc-25',
    type: 'documentary',
    title: 'Chip War',
    year: 2024,
    creator: 'PBS Frontline',
    era: 'Modern Semiconductors',
    description: 'Based on Chris Miller\'s book, exploring the geopolitical battle over semiconductor manufacturing, from TSMC\'s dominance to US-China tech rivalry.',
    whereToAccess: 'PBS, YouTube',
    tags: ['semiconductors', 'tsmc', 'geopolitics', 'manufacturing', 'chips'],
  },
  {
    id: 'doc-26',
    type: 'documentary',
    title: 'The Social Network',
    year: 2010,
    creator: 'David Fincher',
    era: 'Social Media Era',
    description: 'The founding of Facebook at Harvard, dramatizing how a dorm-room project became a global platform — exploring ambition, intellectual property, and the human cost of disruption.',
    whereToAccess: 'Netflix, Amazon Prime',
    tags: ['facebook', 'social-media', 'startup', 'harvard', 'zuckerberg'],
  },
  {
    id: 'doc-27',
    type: 'documentary',
    title: 'Citizenfour',
    year: 2014,
    creator: 'Laura Poitras',
    era: 'Surveillance Era',
    description: 'Academy Award-winning documentary filmed in real time as Edward Snowden reveals the NSA\'s mass surveillance programs to journalists in a Hong Kong hotel room.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['snowden', 'nsa', 'surveillance', 'privacy', 'whistleblower'],
  },
  {
    id: 'doc-28',
    type: 'documentary',
    title: 'The Social Dilemma',
    year: 2020,
    creator: 'Jeff Orlowski',
    era: 'Modern',
    description: 'Tech insiders reveal how social media platforms are designed to exploit human psychology — algorithms, attention economics, and the business model of addiction.',
    whereToAccess: 'Netflix',
    tags: ['social-media', 'algorithms', 'psychology', 'attention', 'ethics'],
  },
  {
    id: 'doc-29',
    type: 'documentary',
    title: 'The Great Hack',
    year: 2019,
    creator: 'Karim Amer & Jehane Noujaim',
    era: 'Data Era',
    description: 'The Cambridge Analytica scandal exposed — how personal data was weaponized to influence elections, raising fundamental questions about data rights and democracy.',
    whereToAccess: 'Netflix',
    tags: ['cambridge-analytica', 'data', 'privacy', 'elections', 'facebook'],
  },
  {
    id: 'doc-30',
    type: 'documentary',
    title: 'Coded Bias',
    year: 2020,
    creator: 'Shalini Kantayya',
    era: 'AI Era',
    description: 'MIT researcher Joy Buolamwini discovers racial bias in facial recognition AI, launching an investigation into how algorithms perpetuate discrimination.',
    whereToAccess: 'Netflix, Amazon Prime',
    tags: ['ai-bias', 'facial-recognition', 'ethics', 'discrimination', 'algorithms'],
  },
  {
    id: 'doc-31',
    type: 'documentary',
    title: 'Downloaded',
    year: 2013,
    creator: 'Alex Winter',
    era: 'Internet Era',
    description: 'The rise and fall of Napster — how two teenagers built a file-sharing service that terrified the music industry and redefined how we consume digital media.',
    whereToAccess: 'YouTube, Amazon Prime',
    tags: ['napster', 'file-sharing', 'music', 'piracy', 'p2p'],
  },
  {
    id: 'doc-32',
    type: 'documentary',
    title: 'Indie Game: The Movie',
    year: 2012,
    creator: 'Lisanne Pajot & James Swirsky',
    era: 'Modern',
    description: 'Follows the creators of Super Meat Boy, Fez, and Braid through the emotional rollercoaster of independent game development — art, code, and obsession.',
    whereToAccess: 'Netflix, Steam',
    tags: ['indie-games', 'game-development', 'programming', 'creativity'],
  },
  {
    id: 'doc-33',
    type: 'documentary',
    title: 'High Score',
    year: 2020,
    creator: 'Netflix',
    era: 'Gaming History',
    description: 'Six-part Netflix series tracing the golden age of video games — from Space Invaders and Pac-Man to Doom and the rise of 3D graphics, told through the engineers who built them.',
    whereToAccess: 'Netflix',
    tags: ['gaming', 'arcade', 'console', '3d-graphics', 'history'],
  },
  {
    id: 'doc-34',
    type: 'documentary',
    title: 'The Secret Rules of Modern Living: Algorithms',
    year: 2015,
    creator: 'BBC',
    era: 'Modern',
    description: 'Professor Marcus du Sautoy demystifies the algorithms that run our world — from search engines to recommendation systems, showing the hidden math behind everyday technology.',
    whereToAccess: 'BBC iPlayer, YouTube',
    tags: ['algorithms', 'search', 'sorting', 'optimization', 'mathematics'],
  },
  {
    id: 'doc-35',
    type: 'documentary',
    title: 'DEFCON: The Documentary',
    year: 2013,
    creator: 'Jason Scott',
    era: 'Hacker Culture',
    description: 'Inside the world\'s largest hacker convention — social engineers, lock pickers, hardware hackers, and security researchers gather in Las Vegas to share knowledge and compete.',
    whereToAccess: 'YouTube (free)',
    tags: ['defcon', 'hacking', 'security', 'convention', 'culture'],
  },
  {
    id: 'doc-36',
    type: 'documentary',
    title: 'Sneakers',
    year: 1992,
    creator: 'Phil Alden Robinson',
    era: 'Cryptography',
    description: 'A team of security experts is blackmailed into stealing a device that can break any encryption system. A prescient thriller about cryptography, privacy, and the power of information.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['cryptography', 'encryption', 'hacking', 'security', 'thriller'],
  },
  {
    id: 'doc-37',
    type: 'documentary',
    title: 'WarGames',
    year: 1983,
    creator: 'John Badham',
    era: 'Cold War Computing',
    description: 'A teenage hacker accidentally connects to a military supercomputer and nearly starts WWIII. The film that introduced an entire generation to modems, hacking, and the concept of AI.',
    whereToAccess: 'Amazon Prime, YouTube',
    tags: ['hacking', 'cold-war', 'ai', 'modem', 'military', 'classic'],
  },
  {
    id: 'doc-38',
    type: 'documentary',
    title: 'Deep Web',
    year: 2015,
    creator: 'Alex Winter',
    era: 'Cryptography Era',
    description: 'The story of the Silk Road marketplace and its creator Ross Ulbricht — exploring the dark web, cryptocurrency, privacy technology, and the clash between freedom and law.',
    whereToAccess: 'Amazon Prime',
    tags: ['silk-road', 'dark-web', 'cryptocurrency', 'tor', 'privacy'],
  },
];

// --- Story 20.8: TV Shows & Series ---

const TV_SHOWS: readonly CuratedResource[] = [
  {
    id: 'tv-01',
    type: 'tv',
    title: 'Halt and Catch Fire',
    year: 2014,
    creator: 'AMC',
    era: 'PC Era (1980s-90s)',
    description: 'Drama following engineers and entrepreneurs racing to build the future of computing, from PC clones to the early internet, capturing the ambition and chaos of Silicon Prairie.',
    whereToAccess: 'AMC+, Amazon Prime',
    tags: ['pc-era', 'ibm-clone', 'networking', 'internet', 'startup'],
  },
  {
    id: 'tv-02',
    type: 'tv',
    title: 'Silicon Valley',
    year: 2014,
    creator: 'HBO',
    era: 'Modern',
    description: 'Comedy satirizing the modern tech startup world — compression algorithms, venture capital, and the absurdity of building a billion-dollar company from nothing.',
    whereToAccess: 'HBO Max',
    tags: ['startup', 'silicon-valley', 'compression', 'modern-tech'],
  },
  {
    id: 'tv-03',
    type: 'tv',
    title: 'The Billion Dollar Code',
    year: 2021,
    creator: 'Netflix',
    era: 'Modern',
    description: 'German miniseries about the true story of two hackers who invented the technology behind Google Earth, and their legal battle for recognition.',
    whereToAccess: 'Netflix',
    tags: ['google-earth', 'mapping', 'patent', 'hacker'],
  },
  {
    id: 'tv-04',
    type: 'tv',
    title: 'Devs',
    year: 2020,
    creator: 'Hulu/FX',
    era: 'Modern',
    description: 'Thriller exploring quantum computing, determinism, and the limits of simulation — a secretive Silicon Valley lab builds something that could predict the future.',
    whereToAccess: 'Hulu, Disney+',
    tags: ['quantum', 'simulation', 'silicon-valley', 'determinism'],
  },
  {
    id: 'tv-05',
    type: 'tv',
    title: 'Mr. Robot',
    year: 2015,
    creator: 'USA Network',
    era: 'Cybersecurity',
    description: 'A cybersecurity engineer and hacker joins an underground group aiming to take down a powerful corporation. Praised for its technical accuracy in depicting hacking, encryption, and social engineering.',
    whereToAccess: 'Amazon Prime',
    tags: ['hacking', 'cybersecurity', 'encryption', 'social-engineering', 'linux'],
  },
  {
    id: 'tv-06',
    type: 'tv',
    title: 'Black Mirror',
    year: 2011,
    creator: 'Netflix / Channel 4',
    era: 'Near Future',
    description: 'Anthology series exploring the dark side of technology — each episode imagines how current tech trends could evolve into dystopian scenarios, from social scoring to digital consciousness.',
    whereToAccess: 'Netflix',
    tags: ['dystopia', 'ai', 'social-media', 'surveillance', 'near-future'],
  },
  {
    id: 'tv-07',
    type: 'tv',
    title: 'Person of Interest',
    year: 2011,
    creator: 'CBS',
    era: 'AI Surveillance',
    description: 'A billionaire programmer builds an AI surveillance system that predicts crimes before they happen. Explores machine intelligence, privacy, and the ethics of omniscient computing.',
    whereToAccess: 'Amazon Prime, HBO Max',
    tags: ['ai', 'surveillance', 'privacy', 'machine-learning', 'ethics'],
  },
  {
    id: 'tv-08',
    type: 'tv',
    title: 'The IT Crowd',
    year: 2006,
    creator: 'Channel 4',
    era: 'Modern',
    description: 'British comedy set in the basement IT department of a large corporation. A love letter to tech culture, awkward debugging, and the eternal question: "Have you tried turning it off and on again?"',
    whereToAccess: 'Netflix, Britbox',
    tags: ['comedy', 'it-culture', 'tech-support', 'british-computing'],
  },
  {
    id: 'tv-09',
    type: 'tv',
    title: 'Severance',
    year: 2022,
    creator: 'Apple TV+',
    era: 'Near Future',
    description: 'Employees undergo a procedure to separate work and personal memories. A thriller about consciousness, data, and what happens when you can partition the human mind like a hard drive.',
    whereToAccess: 'Apple TV+',
    tags: ['consciousness', 'memory', 'corporate', 'thriller', 'partition'],
  },
  {
    id: 'tv-10',
    type: 'tv',
    title: 'The Playlist',
    year: 2022,
    creator: 'Netflix',
    era: 'Modern',
    description: 'The origin story of Spotify, told from six different perspectives — the coders, the music industry, the pirates, and the venture capitalists who made streaming music possible.',
    whereToAccess: 'Netflix',
    tags: ['spotify', 'streaming', 'startup', 'music', 'piracy'],
  },
  {
    id: 'tv-11',
    type: 'tv',
    title: 'Pantheon',
    year: 2022,
    creator: 'AMC+',
    era: 'Near Future',
    description: 'Animated sci-fi series about uploaded human intelligences running on servers. Explores what happens when human minds become software — consciousness as code.',
    whereToAccess: 'AMC+',
    tags: ['mind-uploading', 'ai', 'consciousness', 'animation', 'transhumanism'],
  },
  {
    id: 'tv-12',
    type: 'tv',
    title: 'Westworld',
    year: 2016,
    creator: 'HBO',
    era: 'AI & Robotics',
    description: 'AI-powered androids in a theme park begin developing consciousness. A philosophical exploration of artificial intelligence, free will, and what it means to be sentient.',
    whereToAccess: 'HBO Max',
    tags: ['ai', 'robotics', 'consciousness', 'free-will', 'simulation'],
  },
  {
    id: 'tv-13',
    type: 'tv',
    title: 'Battlestar Galactica',
    year: 2004,
    creator: 'Syfy',
    era: 'AI & Robotics',
    description: 'Humanity fights for survival against the Cylons — AI creations that evolved beyond their programming. Explores what happens when artificial intelligence achieves consciousness and decides to rebel.',
    whereToAccess: 'Peacock, Amazon Prime',
    tags: ['ai', 'robotics', 'consciousness', 'space', 'rebellion'],
  },
  {
    id: 'tv-14',
    type: 'tv',
    title: 'Humans',
    year: 2015,
    creator: 'Channel 4 / AMC',
    era: 'Near Future',
    description: 'In a parallel present, lifelike humanoid robots called Synths serve as domestic helpers. When some develop consciousness, society must confront what it means to be alive.',
    whereToAccess: 'Amazon Prime',
    tags: ['ai', 'robotics', 'consciousness', 'domestic', 'ethics'],
  },
  {
    id: 'tv-15',
    type: 'tv',
    title: 'The Capture',
    year: 2019,
    creator: 'BBC',
    era: 'Surveillance',
    description: 'A British soldier is framed using deepfake CCTV footage, exposing a conspiracy involving AI-manipulated video surveillance. A prescient thriller about the fragility of digital evidence.',
    whereToAccess: 'BBC iPlayer, Peacock',
    tags: ['deepfake', 'surveillance', 'ai', 'evidence', 'conspiracy'],
  },
  {
    id: 'tv-16',
    type: 'tv',
    title: 'Upload',
    year: 2020,
    creator: 'Amazon',
    era: 'Near Future',
    description: 'Comedy-drama set in a future where people can upload their consciousness to a digital afterlife. Explores cloud computing, digital class divides, and what happens when your soul runs on servers.',
    whereToAccess: 'Amazon Prime',
    tags: ['mind-uploading', 'cloud', 'digital-afterlife', 'comedy', 'class'],
  },
  {
    id: 'tv-17',
    type: 'tv',
    title: 'Reboot',
    year: 1994,
    creator: 'Mainframe Entertainment',
    era: 'Early CGI',
    description: 'The first fully computer-generated TV series, set inside a computer where characters defend the system from viruses and the chaos of "The User" playing games.',
    whereToAccess: 'YouTube, Archive.org',
    tags: ['cgi', 'animation', 'inside-computer', 'virus', 'pioneering'],
  },
  {
    id: 'tv-18',
    type: 'tv',
    title: 'Scorpion',
    year: 2014,
    creator: 'CBS',
    era: 'Modern',
    description: 'Loosely inspired by the life of Walter O\'Brien, a team of genius hackers and engineers solve high-tech crises for Homeland Security using programming, networking, and unconventional engineering.',
    whereToAccess: 'Paramount+, Amazon Prime',
    tags: ['hacking', 'engineering', 'team', 'crisis', 'genius'],
  },
  {
    id: 'tv-19',
    type: 'tv',
    title: 'Electric Dreams',
    year: 2017,
    creator: 'Amazon / Channel 4',
    era: 'Sci-Fi Futures',
    description: 'Anthology series based on Philip K. Dick\'s short stories, exploring futures shaped by technology — from android servants to memory manipulation and virtual reality.',
    whereToAccess: 'Amazon Prime',
    tags: ['philip-k-dick', 'anthology', 'android', 'memory', 'virtual-reality'],
  },
  {
    id: 'tv-20',
    type: 'tv',
    title: 'Mythic Quest',
    year: 2020,
    creator: 'Apple TV+',
    era: 'Modern',
    description: 'Comedy about the dysfunctional team behind a massive multiplayer online game. Skewers the game development industry while exploring creativity, crunch culture, and the business of interactive entertainment.',
    whereToAccess: 'Apple TV+',
    tags: ['game-development', 'comedy', 'startup', 'gaming', 'culture'],
  },
];

// --- Story 20.9: YouTube Channels & Videos ---

const YOUTUBE: readonly CuratedResource[] = [
  {
    id: 'yt-01',
    type: 'youtube',
    title: 'Ben Eater',
    creator: 'Ben Eater',
    era: 'Hands-On Building',
    description: 'Build an 8-bit computer from scratch on a breadboard. The definitive hands-on series for understanding how CPUs work at the gate level.',
    whereToAccess: 'youtube.com/@BenEater',
    tags: ['breadboard', '8-bit', 'cpu-building', 'hands-on', 'gates'],
  },
  {
    id: 'yt-02',
    type: 'youtube',
    title: 'Computerphile',
    creator: 'Brady Haran / University of Nottingham',
    era: 'CS Concepts',
    description: 'Academic computer science explained accessibly — from Turing machines to modern cryptography, featuring university professors.',
    whereToAccess: 'youtube.com/@Computerphile',
    tags: ['cs-concepts', 'turing', 'algorithms', 'cryptography', 'academic'],
  },
  {
    id: 'yt-03',
    type: 'youtube',
    title: 'The 8-Bit Guy',
    creator: 'David Murray',
    era: '8-bit & 16-bit',
    description: 'Exploring, restoring, and explaining vintage 8-bit and 16-bit computers — Commodore 64, Apple II, DOS-era PCs, and more.',
    whereToAccess: 'youtube.com/@The8BitGuy',
    tags: ['retro', '8-bit', '16-bit', 'commodore', 'apple-ii', 'restoration'],
  },
  {
    id: 'yt-04',
    type: 'youtube',
    title: 'LGR (Lazy Game Reviews)',
    creator: 'Clint Basinger',
    era: 'IBM PC Era',
    description: 'Deep dives into IBM PC-compatible hardware, DOS software, and the culture of 1990s computing with detailed teardowns and reviews.',
    whereToAccess: 'youtube.com/@LGR',
    tags: ['ibm-pc', 'dos', '90s', 'hardware', 'teardown'],
  },
  {
    id: 'yt-05',
    type: 'youtube',
    title: 'Technology Connections',
    creator: 'Alec Watson',
    era: 'Electronics Fundamentals',
    description: 'Deep explanations of how everyday technology works, from analog circuits to digital logic, with a focus on the engineering "why" behind designs.',
    whereToAccess: 'youtube.com/@TechnologyConnections',
    tags: ['electronics', 'analog', 'digital', 'engineering', 'fundamentals'],
  },
  {
    id: 'yt-06',
    type: 'youtube',
    title: 'CuriousMarc',
    creator: 'Marc Verdiell',
    era: 'Vintage Restoration',
    description: 'Restoring and repairing iconic vintage computers including the Apollo Guidance Computer, HP calculators, and Xerox Alto.',
    whereToAccess: 'youtube.com/@CuriousMarc',
    tags: ['restoration', 'apollo', 'vintage', 'hp', 'xerox-alto'],
  },
  {
    id: 'yt-07',
    type: 'youtube',
    title: 'Usagi Electric',
    creator: 'David Lovett',
    era: 'Pre-transistor Computing',
    description: 'Building computers from vacuum tubes and relays, exploring the technology that preceded transistors with hands-on construction.',
    whereToAccess: 'youtube.com/@UsagiElectric',
    tags: ['vacuum-tube', 'relay', 'pre-transistor', 'hands-on'],
  },
  {
    id: 'yt-08',
    type: 'youtube',
    title: 'Sebastian Lague',
    creator: 'Sebastian Lague',
    era: 'Visual CS',
    description: 'Beautiful visualizations of computer science concepts — ray tracing, pathfinding, neural networks, and more, explained through code and animation.',
    whereToAccess: 'youtube.com/@SebastianLague',
    tags: ['visualization', 'algorithms', 'graphics', 'animation'],
  },
  {
    id: 'yt-09',
    type: 'youtube',
    title: '3Blue1Brown',
    creator: 'Grant Sanderson',
    era: 'Math & CS Foundations',
    description: 'Stunning animated math explanations that illuminate the foundations of computing — neural networks, information theory, linear algebra, and the math behind encryption.',
    whereToAccess: 'youtube.com/@3blue1brown',
    tags: ['math', 'neural-networks', 'linear-algebra', 'visualization', 'animation'],
  },
  {
    id: 'yt-10',
    type: 'youtube',
    title: 'Crash Course Computer Science',
    creator: 'Carrie Anne Philbin / PBS',
    era: 'All Eras',
    description: 'Complete 40-episode CS curriculum from Boolean logic to AI, tracing the full history of computing. Perfect companion to the Digital Archaeology story.',
    whereToAccess: 'youtube.com/@crashcourse (CS playlist)',
    tags: ['curriculum', 'history', 'boolean', 'cpu', 'ai', 'comprehensive'],
  },
  {
    id: 'yt-11',
    type: 'youtube',
    title: 'Tom Scott',
    creator: 'Tom Scott',
    era: 'Modern Tech',
    description: 'Short, punchy explanations of fascinating technical concepts — Unicode, GPS, why computers can\'t generate truly random numbers, and more.',
    whereToAccess: 'youtube.com/@TomScottGo',
    tags: ['unicode', 'gps', 'networking', 'short-form', 'explainer'],
  },
  {
    id: 'yt-12',
    type: 'youtube',
    title: 'LiveOverflow',
    creator: 'LiveOverflow',
    era: 'Security & Hacking',
    description: 'Binary exploitation, reverse engineering, and CTF challenges explained with clarity. Learn how hackers think and how software breaks at the lowest levels.',
    whereToAccess: 'youtube.com/@LiveOverflow',
    tags: ['hacking', 'binary', 'reverse-engineering', 'security', 'ctf'],
  },
  {
    id: 'yt-13',
    type: 'youtube',
    title: 'Low Level Learning',
    creator: 'Low Level Learning',
    era: 'Systems Programming',
    description: 'Rust, C, assembly, and systems programming explained from the ground up. Covers how CPUs execute code, memory management, and low-level optimization.',
    whereToAccess: 'youtube.com/@LowLevelLearning',
    tags: ['systems', 'rust', 'c', 'assembly', 'memory', 'low-level'],
  },
  {
    id: 'yt-14',
    type: 'youtube',
    title: 'Retro Game Mechanics Explained',
    creator: 'RGME',
    era: 'Console Hardware',
    description: 'How classic game consoles actually work at the hardware level — the NES PPU, SNES Mode 7, Genesis blast processing, and the clever hacks developers used.',
    whereToAccess: 'youtube.com/@RetroGameMechanicsExplained',
    tags: ['nes', 'snes', 'console', 'hardware', 'graphics', 'retro'],
  },
  {
    id: 'yt-15',
    type: 'youtube',
    title: 'EEVblog',
    creator: 'Dave Jones',
    era: 'Electronics Engineering',
    description: 'Electronics engineering blog covering oscilloscopes, PCB design, component teardowns, and the fundamentals of analog and digital electronics.',
    whereToAccess: 'youtube.com/@EEVblog',
    tags: ['electronics', 'pcb', 'oscilloscope', 'teardown', 'engineering'],
  },
  {
    id: 'yt-16',
    type: 'youtube',
    title: 'The Coding Train',
    creator: 'Daniel Shiffman',
    era: 'Creative Coding',
    description: 'Joyful creative coding tutorials — build fractals, simulations, neural networks, and generative art while learning fundamental CS concepts.',
    whereToAccess: 'youtube.com/@TheCodingTrain',
    tags: ['creative-coding', 'simulation', 'fractals', 'neural-networks', 'generative'],
  },
  {
    id: 'yt-17',
    type: 'youtube',
    title: 'Two Minute Papers',
    creator: 'Dr. Karoly Zsolnai-Feher',
    era: 'AI Research',
    description: 'Summaries of cutting-edge AI and graphics research papers — neural radiance fields, diffusion models, physics simulation, and more, explained in accessible terms.',
    whereToAccess: 'youtube.com/@TwoMinutePapers',
    tags: ['ai', 'research', 'graphics', 'neural-networks', 'papers'],
  },
  {
    id: 'yt-18',
    type: 'youtube',
    title: 'Fireship',
    creator: 'Jeff Delaney',
    era: 'Modern Dev',
    description: 'Fast-paced, witty explainers of programming languages, frameworks, and tech news in 100 seconds or less. Covers everything from assembly to Rust to the latest web frameworks.',
    whereToAccess: 'youtube.com/@Fireship',
    tags: ['web-dev', 'languages', 'frameworks', 'news', 'short-form'],
  },
  {
    id: 'yt-19',
    type: 'youtube',
    title: 'Neso Academy',
    creator: 'Neso Academy',
    era: 'CS Foundations',
    description: 'Comprehensive computer science lectures covering digital electronics, computer organization, operating systems, and compiler design — a full university curriculum for free.',
    whereToAccess: 'youtube.com/@nesoacademy',
    tags: ['digital-electronics', 'computer-organization', 'os', 'compiler', 'lectures'],
  },
  {
    id: 'yt-20',
    type: 'youtube',
    title: 'Adrian\'s Digital Basement',
    creator: 'Adrian Black',
    era: 'Retro Computing',
    description: 'Repairing and restoring vintage computers and gaming hardware — from Commodore PETs to early Macs, with detailed troubleshooting and soldering work.',
    whereToAccess: 'youtube.com/@adriansdigitalbasement',
    tags: ['retro', 'repair', 'restoration', 'commodore', 'vintage'],
  },
  {
    id: 'yt-21',
    type: 'youtube',
    title: 'Ahoy',
    creator: 'Stuart Brown',
    era: 'Gaming & Computing History',
    description: 'Beautifully produced documentaries about gaming and computing history — the story of the video game crash, the history of the first-person shooter, and nuclear bunker computers.',
    whereToAccess: 'youtube.com/@XboxAhoy',
    tags: ['gaming', 'history', 'documentary', 'production', 'storytelling'],
  },
  {
    id: 'yt-22',
    type: 'youtube',
    title: 'javidx9 / OneLoneCoder',
    creator: 'David Barr',
    era: 'Systems Programming',
    description: 'Programming from scratch in C++ — build game engines, emulators, and CPU simulators from first principles, with clear explanations of low-level concepts.',
    whereToAccess: 'youtube.com/@javidx9',
    tags: ['cpp', 'emulator', 'game-engine', 'from-scratch', 'low-level'],
  },
  {
    id: 'yt-23',
    type: 'youtube',
    title: 'Reducible',
    creator: 'Reducible',
    era: 'Algorithms & Data Structures',
    description: 'Elegant animated explanations of algorithms and data structures — FFT, graph algorithms, compression, and the mathematical ideas that power modern computing.',
    whereToAccess: 'youtube.com/@Reducible',
    tags: ['algorithms', 'data-structures', 'fft', 'animation', 'mathematics'],
  },
  {
    id: 'yt-24',
    type: 'youtube',
    title: 'Computerphile / Numberphile',
    creator: 'Brady Haran',
    era: 'Math & CS',
    description: 'Numberphile, the sister channel to Computerphile, covers the mathematics underlying computing — from prime numbers to cryptography to infinity, with university mathematicians.',
    whereToAccess: 'youtube.com/@numberphile',
    tags: ['mathematics', 'primes', 'cryptography', 'infinity', 'academic'],
  },
  {
    id: 'yt-25',
    type: 'youtube',
    title: 'Dave\'s Garage',
    creator: 'Dave Plummer',
    era: 'Windows History',
    description: 'Former Microsoft engineer who wrote Task Manager shares insider stories about Windows development, OS internals, and the culture of building software at scale.',
    whereToAccess: 'youtube.com/@DavesGarage',
    tags: ['windows', 'microsoft', 'os-internals', 'insider', 'task-manager'],
  },
];

// --- Story 20.10: Books ---

const BOOKS: readonly CuratedResource[] = [
  {
    id: 'book-01',
    type: 'book',
    title: 'Code: The Hidden Language of Computer Hardware and Software',
    creator: 'Charles Petzold',
    year: 2000,
    era: 'First Principles',
    description: 'The definitive guide to understanding computers from scratch — from Morse code and flashlights to building a complete CPU, one layer at a time.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['fundamentals', 'hardware', 'gates', 'cpu', 'first-principles'],
  },
  {
    id: 'book-02',
    type: 'book',
    title: 'The Innovators',
    creator: 'Walter Isaacson',
    year: 2014,
    era: 'All Eras',
    description: 'How a group of hackers, geniuses, and geeks created the digital revolution — from Ada Lovelace to Google, tracing the collaborative nature of innovation.',
    whereToAccess: 'Amazon, bookstores, libraries',
    tags: ['history', 'lovelace', 'turing', 'innovation', 'collaboration'],
  },
  {
    id: 'book-03',
    type: 'book',
    title: 'The Soul of a New Machine',
    creator: 'Tracy Kidder',
    year: 1981,
    era: 'Minicomputer Era',
    description: 'Pulitzer Prize-winning account of building a new minicomputer at Data General, capturing the intensity and human drama of hardware engineering.',
    whereToAccess: 'Amazon, bookstores, libraries',
    tags: ['minicomputer', 'hardware', 'engineering', 'data-general'],
  },
  {
    id: 'book-04',
    type: 'book',
    title: 'Hackers: Heroes of the Computer Revolution',
    creator: 'Steven Levy',
    year: 1984,
    era: 'PC Era',
    description: 'The hacker ethic from MIT to the Homebrew Computer Club — how passionate tinkerers built the foundations of personal computing.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['hacker', 'mit', 'homebrew', 'pc-revolution', 'culture'],
  },
  {
    id: 'book-05',
    type: 'book',
    title: 'Fire in the Valley',
    creator: 'Michael Swaine & Paul Freiberger',
    year: 1984,
    era: 'PC Revolution',
    description: 'The making of the personal computer from the Altair 8800 to the IBM PC, with insider accounts from the people who built the industry.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['altair', 'ibm-pc', 'apple', 'pc-revolution'],
  },
  {
    id: 'book-06',
    type: 'book',
    title: 'The Dream Machine',
    creator: 'M. Mitchell Waldrop',
    year: 2001,
    era: 'Mainframe to Internet',
    description: 'The story of J.C.R. Licklider, who envisioned human-computer symbiosis and funded the creation of the ARPANET, shaping the future of computing.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['licklider', 'arpanet', 'darpa', 'internet', 'mainframe'],
  },
  {
    id: 'book-07',
    type: 'book',
    title: "Turing's Cathedral",
    creator: 'George Dyson',
    year: 2012,
    era: 'Dawn of Computing',
    description: 'The origins of the digital universe at the Institute for Advanced Study, where von Neumann and colleagues built one of the first stored-program computers.',
    whereToAccess: 'Amazon, bookstores, libraries',
    tags: ['von-neumann', 'ias', 'stored-program', 'early-computing'],
  },
  {
    id: 'book-08',
    type: 'book',
    title: 'But How Do It Know?',
    creator: 'J. Clark Scott',
    year: 2009,
    era: 'First Principles',
    description: 'A simple, accessible explanation of how computers work from NAND gates to a complete CPU, written for absolute beginners with no prerequisites.',
    whereToAccess: 'Amazon',
    tags: ['fundamentals', 'nand', 'gates', 'cpu', 'beginner'],
  },
  {
    id: 'book-09',
    type: 'book',
    title: 'The Elements of Computing Systems (Nand2Tetris)',
    creator: 'Noam Nisan & Shimon Schocken',
    year: 2005,
    era: 'Build from Gates',
    description: 'The textbook behind Nand2Tetris: build a complete computer system from NAND gates through hardware, assembler, VM, compiler, and OS. The ultimate bottom-up learning path.',
    whereToAccess: 'Amazon, MIT Press',
    tags: ['nand2tetris', 'gates', 'assembler', 'compiler', 'os', 'hands-on'],
  },
  {
    id: 'book-10',
    type: 'book',
    title: 'Alan Turing: The Enigma',
    creator: 'Andrew Hodges',
    year: 1983,
    era: 'Turing Era',
    description: 'The definitive biography of Alan Turing — his mathematical genius, his wartime codebreaking, his vision of thinking machines, and his tragic end.',
    whereToAccess: 'Amazon, bookstores, libraries',
    tags: ['turing', 'biography', 'enigma', 'ai', 'mathematics'],
  },
  {
    id: 'book-11',
    type: 'book',
    title: 'Chip War',
    creator: 'Chris Miller',
    year: 2022,
    era: 'Semiconductor Era',
    description: 'How the global fight over microchip technology shapes the modern world — from the invention of the transistor to today\'s US-China semiconductor rivalry.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['semiconductors', 'geopolitics', 'transistor', 'tsmc', 'intel'],
  },
  {
    id: 'book-12',
    type: 'book',
    title: 'Crystal Fire: The Invention of the Transistor',
    creator: 'Michael Riordan & Lillian Hoddeson',
    year: 1997,
    era: 'Transistor Era',
    description: 'The dramatic story of how Shockley, Bardeen, and Brattain invented the transistor at Bell Labs — the device that made all modern computing possible.',
    whereToAccess: 'Amazon, libraries',
    tags: ['transistor', 'bell-labs', 'shockley', 'bardeen', 'semiconductor'],
  },
  {
    id: 'book-13',
    type: 'book',
    title: 'The Cuckoo\'s Egg',
    creator: 'Clifford Stoll',
    year: 1989,
    era: 'Early Internet',
    description: 'A true cyber-detective story: an astronomer traces a 75-cent accounting discrepancy to a German hacker working for the KGB. The original cybersecurity thriller.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['hacking', 'kgb', 'cybersecurity', 'cold-war', 'true-crime'],
  },
  {
    id: 'book-14',
    type: 'book',
    title: 'Dealers of Lightning: Xerox PARC and the Dawn of the Computer Age',
    creator: 'Michael Hiltzik',
    year: 1999,
    era: 'PC Origins',
    description: 'Inside Xerox PARC, where researchers invented the GUI, Ethernet, laser printing, and object-oriented programming — then watched others profit from their innovations.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['xerox-parc', 'gui', 'ethernet', 'laser-printer', 'innovation'],
  },
  {
    id: 'book-15',
    type: 'book',
    title: 'Where Wizards Stay Up Late',
    creator: 'Katie Hafner & Matthew Lyon',
    year: 1996,
    era: 'ARPANET',
    description: 'The origins of the internet — how a small group of engineers at BBN and university labs built the ARPANET, creating the network that became the internet.',
    whereToAccess: 'Amazon, libraries',
    tags: ['arpanet', 'internet', 'bbn', 'networking', 'darpa'],
  },
  {
    id: 'book-16',
    type: 'book',
    title: 'Just for Fun: The Story of an Accidental Revolutionary',
    creator: 'Linus Torvalds & David Diamond',
    year: 2001,
    era: 'Open Source',
    description: 'Linus Torvalds\' autobiography — how a Finnish student\'s hobby project became the Linux kernel that runs most of the world\'s servers, phones, and supercomputers.',
    whereToAccess: 'Amazon, libraries',
    tags: ['linux', 'torvalds', 'open-source', 'autobiography', 'kernel'],
  },
  {
    id: 'book-17',
    type: 'book',
    title: 'iWoz: Computer Geek to Cult Icon',
    creator: 'Steve Wozniak & Gina Smith',
    year: 2006,
    era: 'PC Revolution',
    description: 'Steve Wozniak\'s own story of building the Apple I and Apple II from scratch, his engineering philosophy, and the garage days that launched the personal computer revolution.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['wozniak', 'apple', 'apple-ii', 'hardware', 'autobiography'],
  },
  {
    id: 'book-18',
    type: 'book',
    title: 'The Man from the Future: The Visionary Life of John von Neumann',
    creator: 'Ananyo Bhattacharya',
    year: 2022,
    era: 'Dawn of Computing',
    description: 'Biography of the polymath who shaped computer architecture, game theory, nuclear weapons, and cellular automata — the stored-program concept that underlies every modern computer.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['von-neumann', 'architecture', 'game-theory', 'biography', 'mathematics'],
  },
  {
    id: 'book-19',
    type: 'book',
    title: 'Showstopper! The Breakneck Race to Create Windows NT',
    creator: 'G. Pascal Zachary',
    year: 1994,
    era: 'OS Wars',
    description: 'Inside the pressure-cooker development of Windows NT under Dave Cutler, revealing how a small team of engineers built the operating system that would power enterprise computing for decades.',
    whereToAccess: 'Amazon, libraries',
    tags: ['windows-nt', 'cutler', 'microsoft', 'os', 'engineering'],
  },
  {
    id: 'book-20',
    type: 'book',
    title: 'The Art of Electronics',
    creator: 'Paul Horowitz & Winfield Hill',
    year: 1980,
    era: 'Electronics Fundamentals',
    description: 'The bible of electronics engineering — covers everything from resistors to microprocessors with practical wisdom. The book that taught generations of engineers how circuits actually work.',
    whereToAccess: 'Amazon, university bookstores',
    tags: ['electronics', 'circuits', 'engineering', 'analog', 'digital'],
  },
  {
    id: 'book-21',
    type: 'book',
    title: 'The Mythical Man-Month',
    creator: 'Frederick Brooks',
    year: 1975,
    era: 'Mainframe Era',
    description: 'Lessons from managing the IBM System/360 project — why adding more programmers to a late project makes it later. The foundational text on software project management.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['project-management', 'ibm', 'system-360', 'software-engineering', 'classic'],
  },
  {
    id: 'book-22',
    type: 'book',
    title: 'A People\'s History of Computing in the United States',
    creator: 'Joy Lisi Rankin',
    year: 2018,
    era: 'Timesharing Era',
    description: 'Reframes computing history around the students, teachers, and everyday users of timesharing systems in the 1960s-70s — computing as a democratic, communal activity before the PC era.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['timesharing', 'education', 'social-history', 'community', 'mainframe'],
  },
  {
    id: 'book-23',
    type: 'book',
    title: 'Masters of Doom',
    creator: 'David Kushner',
    year: 2003,
    era: 'Gaming',
    description: 'The story of John Carmack and John Romero — how two wildly different personalities created Doom and Quake, revolutionizing 3D graphics and game engines forever.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['doom', 'quake', 'carmack', 'romero', 'game-engine', '3d-graphics'],
  },
  {
    id: 'book-24',
    type: 'book',
    title: 'The Information: A History, a Theory, a Flood',
    creator: 'James Gleick',
    year: 2011,
    era: 'Information Theory',
    description: 'From African talking drums to Claude Shannon\'s information theory to the modern data deluge — the grand story of how humanity learned to encode, transmit, and process information.',
    whereToAccess: 'Amazon, bookstores, libraries',
    tags: ['information-theory', 'shannon', 'encoding', 'history', 'communication'],
  },
  {
    id: 'book-25',
    type: 'book',
    title: 'Broad Band: The Untold Story of the Women Who Made the Internet',
    creator: 'Claire L. Evans',
    year: 2018,
    era: 'All Eras',
    description: 'The forgotten women of computing — from Ada Lovelace to the ENIAC programmers to the hypertext pioneers and community builders who shaped the internet.',
    whereToAccess: 'Amazon, bookstores',
    tags: ['women-in-tech', 'lovelace', 'eniac', 'hypertext', 'internet'],
  },
  {
    id: 'book-26',
    type: 'book',
    title: 'Computer Architecture: A Quantitative Approach',
    creator: 'John Hennessy & David Patterson',
    year: 1990,
    era: 'CPU Architecture',
    description: 'The definitive textbook on computer architecture — RISC vs CISC, pipelining, caching, and memory hierarchies. The reference that shaped how modern processors are designed and taught.',
    whereToAccess: 'Amazon, university bookstores',
    tags: ['architecture', 'risc', 'cisc', 'pipeline', 'cache', 'textbook'],
  },
];

// --- Story 20.11: Museums & Physical Sites ---

const MUSEUMS: readonly CuratedResource[] = [
  {
    id: 'museum-01',
    type: 'museum',
    title: 'Computer History Museum',
    creator: 'Mountain View, CA, USA',
    era: 'All Eras',
    description: 'The world\'s largest collection of computing artifacts — from Babbage\'s Difference Engine to modern AI, with hands-on exhibits and a working PDP-1.',
    whereToAccess: 'computerhistory.org',
    tags: ['comprehensive', 'babbage', 'pdp-1', 'mainframe', 'silicon-valley'],
  },
  {
    id: 'museum-02',
    type: 'museum',
    title: 'Living Computers: Museum + Labs',
    creator: 'Seattle, WA, USA',
    era: 'Mainframe to PC',
    description: 'Working vintage computers you can actually use — from mainframes to early PCs, with hands-on sessions on real hardware from every era.',
    whereToAccess: 'livingcomputers.org',
    tags: ['hands-on', 'mainframe', 'minicomputer', 'working-hardware'],
  },
  {
    id: 'museum-03',
    type: 'museum',
    title: 'Bletchley Park',
    creator: 'Milton Keynes, UK',
    era: 'WWII / Turing Era',
    description: 'The home of WWII codebreaking — see a working Bombe reconstruction, learn about Colossus (the first electronic computer), and walk where Turing worked.',
    whereToAccess: 'bletchleypark.org.uk',
    tags: ['turing', 'enigma', 'colossus', 'bombe', 'wwii'],
  },
  {
    id: 'museum-04',
    type: 'museum',
    title: 'Science Museum',
    creator: 'London, UK',
    era: 'All Eras',
    description: 'Home to Babbage\'s Difference Engine No. 2 replica (which works!), plus extensive computing galleries from mechanical calculators to modern machines.',
    whereToAccess: 'sciencemuseum.org.uk',
    tags: ['babbage', 'difference-engine', 'mechanical', 'british-computing'],
  },
  {
    id: 'museum-05',
    type: 'museum',
    title: 'Heinz Nixdorf MuseumsForum',
    creator: 'Paderborn, Germany',
    era: 'All Eras',
    description: 'The world\'s largest computer museum by floor space — 5,000 years of information technology from cuneiform tablets to modern robotics.',
    whereToAccess: 'hnf.de',
    tags: ['comprehensive', 'european', 'history', 'robotics'],
  },
  {
    id: 'museum-06',
    type: 'museum',
    title: 'Computer Museum of America',
    creator: 'Roswell, GA, USA',
    era: 'PC Era',
    description: 'Extensive collection of Apple, IBM, and gaming hardware with working demonstrations and rotating exhibits on computing culture.',
    whereToAccess: 'computermuseumofamerica.org',
    tags: ['apple', 'ibm', 'gaming', 'pc-era', 'american'],
  },
  {
    id: 'museum-07',
    type: 'museum',
    title: 'The National Museum of Computing',
    creator: 'Bletchley Park, UK',
    era: 'All Eras',
    description: 'Adjacent to Bletchley Park, housing a working Colossus rebuild, a Tunny machine, and a complete BBC Micro gallery — the UK\'s largest collection of working historic computers.',
    whereToAccess: 'tnmoc.org',
    tags: ['colossus', 'tunny', 'bbc-micro', 'working-hardware', 'british-computing'],
  },
  {
    id: 'museum-08',
    type: 'museum',
    title: 'Deutsches Museum',
    creator: 'Munich, Germany',
    era: 'All Eras',
    description: 'One of the world\'s largest science museums, with computing exhibits featuring Zuse\'s Z3 reconstruction, Enigma machines, and the evolution of German computing.',
    whereToAccess: 'deutsches-museum.de',
    tags: ['zuse', 'z3', 'enigma', 'german-computing', 'science'],
  },
  {
    id: 'museum-09',
    type: 'museum',
    title: 'Intel Museum',
    creator: 'Santa Clara, CA, USA',
    era: 'Semiconductor Era',
    description: 'Intel\'s corporate museum tracing the microprocessor from the 4004 to modern chips, with hands-on exhibits about chip manufacturing and Moore\'s Law.',
    whereToAccess: 'intel.com/museum',
    tags: ['intel', '4004', 'microprocessor', 'moores-law', 'manufacturing'],
  },
  {
    id: 'museum-10',
    type: 'museum',
    title: 'Centre for Computing History',
    creator: 'Cambridge, UK',
    era: '8-bit to Modern',
    description: 'Hands-on museum where you can play on working BBC Micros, ZX Spectrums, Commodore 64s, and Amigas — the UK\'s home computing revolution preserved and playable.',
    whereToAccess: 'computinghistory.org.uk',
    tags: ['bbc-micro', 'spectrum', 'commodore', 'hands-on', '8-bit'],
  },
  {
    id: 'museum-11',
    type: 'museum',
    title: 'Mus\u00E9e des Arts et M\u00E9tiers',
    creator: 'Paris, France',
    era: 'Mechanical Era',
    description: 'Houses Pascal\'s original Pascaline calculator, Jacquard looms, and early French computing machines — see the mechanical roots of computation in one of the world\'s oldest technical museums.',
    whereToAccess: 'arts-et-metiers.net',
    tags: ['pascaline', 'pascal', 'jacquard', 'mechanical', 'french-computing'],
  },
  {
    id: 'museum-12',
    type: 'museum',
    title: 'National Cryptologic Museum',
    creator: 'Fort Meade, MD, USA',
    era: 'Cryptography',
    description: 'Adjacent to the NSA, this museum covers the history of code-making and code-breaking, with Enigma machines, cipher devices, and the role of computing in signals intelligence.',
    whereToAccess: 'nsa.gov/museum',
    tags: ['cryptography', 'enigma', 'nsa', 'cipher', 'intelligence'],
  },
  {
    id: 'museum-13',
    type: 'museum',
    title: 'Smithsonian National Museum of American History',
    creator: 'Washington, DC, USA',
    era: 'All Eras',
    description: 'Houses the original ENIAC panels, early Apple and IBM PCs, and a comprehensive "American Enterprise" exhibit tracing technology\'s role in shaping the nation.',
    whereToAccess: 'americanhistory.si.edu',
    tags: ['eniac', 'apple', 'ibm', 'american', 'comprehensive'],
  },
  {
    id: 'museum-14',
    type: 'museum',
    title: 'The Museum of Applied Arts and Sciences (Powerhouse)',
    creator: 'Sydney, Australia',
    era: 'All Eras',
    description: 'Australia\'s largest science museum, with computing exhibits spanning early calculators to modern technology, plus a strong collection of Australian computing history.',
    whereToAccess: 'maas.museum',
    tags: ['australian', 'calculators', 'technology', 'science', 'comprehensive'],
  },
  {
    id: 'museum-15',
    type: 'museum',
    title: 'Museo Nazionale della Scienza e della Tecnologia',
    creator: 'Milan, Italy',
    era: 'All Eras',
    description: 'Italy\'s largest science museum, housed in a 16th-century monastery, featuring exhibits on telecommunications, computing, and Olivetti\'s pioneering Italian computer designs.',
    whereToAccess: 'museoscienza.org',
    tags: ['italian', 'olivetti', 'telecommunications', 'computing', 'european'],
  },
  {
    id: 'museum-16',
    type: 'museum',
    title: 'System Source Computer Museum',
    creator: 'Hunt Valley, MD, USA',
    era: 'Mainframe to PC',
    description: 'Free museum with working vintage systems from mainframes to early PCs — DEC, IBM, and Apple hardware you can interact with, plus a reproduction 1960s computer room.',
    whereToAccess: 'museum.syssrc.com',
    tags: ['free', 'working-hardware', 'dec', 'ibm', 'mainframe', 'hands-on'],
  },
  {
    id: 'museum-17',
    type: 'museum',
    title: 'Museum of Science and Industry',
    creator: 'Chicago, IL, USA',
    era: 'All Eras',
    description: 'Massive science museum with interactive computing exhibits, a captured German U-505 submarine with its Enigma machine, and technology galleries spanning the industrial to digital age.',
    whereToAccess: 'msichicago.org',
    tags: ['enigma', 'u-boat', 'interactive', 'industrial', 'american'],
  },
  {
    id: 'museum-18',
    type: 'museum',
    title: 'Retro Computer Museum',
    creator: 'Leicester, UK',
    era: '8-bit to 32-bit',
    description: 'Entirely hands-on museum dedicated to playable vintage computing — every exhibit is switched on and available to use, from ZX Spectrums to Amigas to arcade cabinets.',
    whereToAccess: 'retrocomputermuseum.co.uk',
    tags: ['hands-on', 'spectrum', 'amiga', 'arcade', 'playable', 'british'],
  },
  {
    id: 'museum-19',
    type: 'museum',
    title: 'MEGA - Museum of Electronic Games & Art',
    creator: 'Various locations, Germany',
    era: 'Gaming History',
    description: 'Traveling museum exhibition showcasing the art and culture of video games, from early arcade machines to modern installations, exploring gaming as a cultural medium.',
    whereToAccess: 'mega-museum.de',
    tags: ['gaming', 'art', 'arcade', 'culture', 'exhibition', 'german'],
  },
  {
    id: 'museum-20',
    type: 'museum',
    title: 'Computer & Communications Museum of Ireland',
    creator: 'Dublin, Ireland',
    era: 'PC Era',
    description: 'Volunteer-run museum preserving Ireland\'s computing heritage, with working vintage PCs, early networking equipment, and exhibits on Ireland\'s role in the global tech industry.',
    whereToAccess: 'computermuseum.ie',
    tags: ['irish', 'pc-era', 'networking', 'volunteer', 'heritage'],
  },
];

// --- Story 20.12: Online Simulators & Interactive Resources ---

const SIMULATORS: readonly CuratedResource[] = [
  {
    id: 'sim-01',
    type: 'simulator',
    title: 'Nand2Tetris',
    creator: 'Noam Nisan & Shimon Schocken',
    era: 'Build from NAND Gates',
    description: 'Build a complete computer system from NAND gates up through an OS — the gold standard for understanding computer architecture from first principles.',
    whereToAccess: 'nand2tetris.org',
    tags: ['nand', 'gates', 'cpu', 'assembler', 'compiler', 'os', 'first-principles'],
  },
  {
    id: 'sim-02',
    type: 'simulator',
    title: 'Visual 6502',
    creator: 'Visual6502.org Team',
    era: '8-bit Transistor Level',
    description: 'See every transistor fire in a real MOS 6502 CPU — the actual chip layout visualized at the transistor level as it executes instructions.',
    whereToAccess: 'visual6502.org',
    tags: ['6502', 'transistor', 'visualization', 'mos', '8-bit'],
  },
  {
    id: 'sim-03',
    type: 'simulator',
    title: 'Digital',
    creator: 'Helmut Neemann',
    era: 'Logic Simulation',
    description: 'Free logic circuit simulator for building and testing digital circuits — from simple gates to complete CPUs with a visual editor.',
    whereToAccess: 'github.com/hneemann/Digital',
    tags: ['logic-gates', 'simulation', 'circuit', 'visual-editor'],
  },
  {
    id: 'sim-04',
    type: 'simulator',
    title: 'Logic.ly',
    creator: 'Logic.ly',
    era: 'Logic Gates',
    description: 'Drag-and-drop logic gate simulator in the browser — build circuits from AND, OR, NOT gates and see signals propagate in real time.',
    whereToAccess: 'logic.ly',
    tags: ['logic-gates', 'browser', 'visual', 'drag-and-drop'],
  },
  {
    id: 'sim-05',
    type: 'simulator',
    title: 'Turing Machine Simulator',
    creator: 'turingmachine.io',
    era: 'Theoretical Computing',
    description: 'Interactive Turing machine with visual tape, head, and state diagram — experiment with the theoretical foundation of all computation.',
    whereToAccess: 'turingmachine.io',
    tags: ['turing-machine', 'theory', 'computation', 'interactive'],
  },
  {
    id: 'sim-06',
    type: 'simulator',
    title: 'MAME',
    creator: 'MAMEdev Team',
    era: 'Hardware Emulation',
    description: 'Multi-system emulator preserving arcade machines and vintage computers in software — experience the actual hardware behavior of thousands of systems.',
    whereToAccess: 'mamedev.org',
    tags: ['emulation', 'arcade', 'vintage', 'preservation'],
  },
  {
    id: 'sim-07',
    type: 'simulator',
    title: 'Logisim Evolution',
    creator: 'Logisim Evolution Team',
    era: 'Logic Simulation',
    description: 'Open-source educational tool for designing and simulating digital logic circuits. Build everything from simple gates to full CPUs with a polished visual interface.',
    whereToAccess: 'github.com/logisim-evolution/logisim-evolution',
    tags: ['logic-gates', 'simulation', 'education', 'open-source', 'cpu'],
  },
  {
    id: 'sim-08',
    type: 'simulator',
    title: 'CircuitVerse',
    creator: 'CircuitVerse.org',
    era: 'Logic Simulation',
    description: 'Free, collaborative digital circuit simulator that runs in the browser. Build and share circuits online with a community of learners and educators.',
    whereToAccess: 'circuitverse.org',
    tags: ['logic-gates', 'browser', 'collaborative', 'education', 'sharing'],
  },
  {
    id: 'sim-09',
    type: 'simulator',
    title: 'PCjs Machines',
    creator: 'Jeff Parsons',
    era: 'IBM PC Emulation',
    description: 'Run a real IBM PC, PC AT, or PC XT in your browser — original BIOS, DOS, and software running on a cycle-accurate JavaScript emulation of the 8088/8086.',
    whereToAccess: 'pcjs.org',
    tags: ['ibm-pc', '8088', 'dos', 'browser', 'emulation'],
  },
  {
    id: 'sim-10',
    type: 'simulator',
    title: 'Falstad Circuit Simulator',
    creator: 'Paul Falstad',
    era: 'Analog & Digital',
    description: 'Real-time interactive circuit simulator showing current flow with animated dots. Build analog and digital circuits and see voltage, current, and waveforms live.',
    whereToAccess: 'falstad.com/circuit',
    tags: ['analog', 'digital', 'circuit', 'real-time', 'visualization'],
  },
  {
    id: 'sim-11',
    type: 'simulator',
    title: 'CPUlator',
    creator: 'Henry Wong',
    era: 'CPU Simulation',
    description: 'Browser-based CPU simulator supporting ARM and MIPS architectures. Write assembly, step through execution, and see registers and memory update in real time.',
    whereToAccess: 'cpulator.01xz.net',
    tags: ['arm', 'mips', 'assembly', 'browser', 'step-debugger'],
  },
  {
    id: 'sim-12',
    type: 'simulator',
    title: 'Easy 6502',
    creator: 'Nick Morgan',
    era: '8-bit Assembly',
    description: 'Learn 6502 assembly language in your browser with a built-in assembler, emulator, and pixel display. The gentlest introduction to assembly programming.',
    whereToAccess: 'skilldrick.github.io/easy6502',
    tags: ['6502', 'assembly', 'browser', 'tutorial', 'beginner'],
  },
  {
    id: 'sim-13',
    type: 'simulator',
    title: 'Compiler Explorer (Godbolt)',
    creator: 'Matt Godbolt',
    era: 'Compilation',
    description: 'See what your code compiles to in real time — type C, C++, Rust, or dozens of other languages and instantly see the assembly output from real compilers.',
    whereToAccess: 'godbolt.org',
    tags: ['compiler', 'assembly', 'optimization', 'real-time', 'browser'],
  },
  {
    id: 'sim-14',
    type: 'simulator',
    title: 'Turing Complete (Game)',
    creator: 'Zachtronics-style',
    era: 'Logic to CPU',
    description: 'Puzzle game where you build a working computer from NAND gates — starting with basic logic and progressing to a full CPU with an architecture you design.',
    whereToAccess: 'store.steampowered.com',
    tags: ['game', 'nand', 'cpu', 'logic-gates', 'puzzle', 'building'],
  },
  {
    id: 'sim-15',
    type: 'simulator',
    title: 'TIS-100',
    creator: 'Zachtronics',
    era: 'Assembly Programming',
    description: 'Program a fictional parallel computer using assembly language to solve puzzles. Learn registers, jumps, and instruction sets through addictive optimization challenges.',
    whereToAccess: 'store.steampowered.com',
    tags: ['assembly', 'puzzle', 'parallel', 'optimization', 'game'],
  },
  {
    id: 'sim-16',
    type: 'simulator',
    title: 'SHENZHEN I/O',
    creator: 'Zachtronics',
    era: 'Embedded Systems',
    description: 'Design circuits and write assembly for fictional microcontrollers to build consumer electronics. The closest a game gets to real embedded systems engineering.',
    whereToAccess: 'store.steampowered.com',
    tags: ['embedded', 'microcontroller', 'assembly', 'circuit', 'puzzle', 'game'],
  },
  {
    id: 'sim-17',
    type: 'simulator',
    title: 'RISC-V Interpreter',
    creator: 'Various / Cornell',
    era: 'Modern CPU Architecture',
    description: 'Browser-based RISC-V assembly interpreter and debugger — write RISC-V assembly, step through execution, and see how the open-source ISA that is reshaping processor design actually works.',
    whereToAccess: 'riscvasm.lukas-mesthaler.at',
    tags: ['risc-v', 'assembly', 'browser', 'open-source', 'isa'],
  },
  {
    id: 'sim-18',
    type: 'simulator',
    title: 'Wireworld',
    creator: 'Various implementations',
    era: 'Cellular Automata',
    description: 'A cellular automaton where you can build working logic gates and circuits from simple rules — electrons flow through wires, creating AND, OR, and NOT gates from pure emergence.',
    whereToAccess: 'wireworld.co (various browser versions)',
    tags: ['cellular-automata', 'logic-gates', 'emergence', 'simulation', 'visual'],
  },
  {
    id: 'sim-19',
    type: 'simulator',
    title: 'NandGame',
    creator: 'nandgame.com',
    era: 'Logic to CPU',
    description: 'Free browser game that challenges you to build a complete computer starting from a single NAND gate — relays, flip-flops, ALU, registers, and ultimately a programmable CPU.',
    whereToAccess: 'nandgame.com',
    tags: ['nand', 'logic-gates', 'cpu', 'browser', 'game', 'free'],
  },
  {
    id: 'sim-20',
    type: 'simulator',
    title: 'Emularity (Internet Archive)',
    creator: 'Internet Archive / Jason Scott',
    era: 'Software Preservation',
    description: 'Thousands of vintage programs, games, and operating systems running in your browser via emulation — MS-DOS, early Windows, classic Mac OS, and hundreds of vintage systems preserved and playable.',
    whereToAccess: 'archive.org/details/softwarelibrary',
    tags: ['emulation', 'preservation', 'dos', 'vintage', 'browser', 'archive'],
  },
];

/** All curated resources across all types */
export const CURATED_RESOURCES: readonly CuratedResource[] = [
  ...DOCUMENTARIES,
  ...TV_SHOWS,
  ...YOUTUBE,
  ...BOOKS,
  ...MUSEUMS,
  ...SIMULATORS,
];

/** Get all resources of a specific type */
export function getResourcesByType(type: CuratedResourceType): readonly CuratedResource[] {
  return CURATED_RESOURCES.filter(r => r.type === type);
}

/** Get the count of resources for a given type */
export function getResourceCount(type: CuratedResourceType): number {
  return CURATED_RESOURCES.filter(r => r.type === type).length;
}

/** Get all unique eras across all resources */
export function getAllEras(): readonly string[] {
  const eras = new Set(CURATED_RESOURCES.map(r => r.era));
  return Array.from(eras).sort();
}
